org.gradle.jvmargs=-XX:+UseParallelGC -Xmx1536m -Xms256m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
org.gradle.workers.max=1
kotlin.compiler.execution.strategy=in-process
kotlin.daemon.jvmargs=-Xmx1024m
android.useAndroidX=false
android.nonTransitiveRClass=true
android.builder.sdkDownload=false
android.aapt2FromMavenOverride=/opt/android-sdk/build-tools/36.0.0/aapt2
kotlin.code.style=official
